"""Public v1.0 domain foundation API."""

from .models import (
    FLEXIBLE_LATEST_START_MULTIPLIER,
    SOFT_LATEST_START_MULTIPLIER,
    TASK_SCHEMA_VERSION,
    MetricStatus,
    MetricValue,
    SlaType,
    TaskRuntime,
    TaskSpec,
    TaskValidationResult,
    TaskState,
    TaskValidationError,
    migrate_legacy_task,
    validate_task_mapping,
    to_legacy_task_dict,
)
from .sla import SlaLimits, SlaPolicy
from .reservations import (
    CommitStatus,
    PathSpec,
    ReleaseStatus,
    Reservation,
    ReservationRequest,
    ReservationValidationError,
    TimeInterval,
    canonical_edge,
)
from .candidates import (
    CANDIDATE_SCHEMA_VERSION,
    Candidate,
    CandidateGenerationStatus,
    CandidateMode,
    CandidateSetResult,
)
from .units import (
    DataUnitConverter,
    TariffConverter,
    TimeConverter,
    UnitValidationError,
    cpu_work_cpu_hours,
    cpu_work_sim_units,
    validate_scheduling_grid,
)


__all__ = [
    "DataUnitConverter",
    "CommitStatus",
    "CANDIDATE_SCHEMA_VERSION",
    "Candidate",
    "CandidateGenerationStatus",
    "CandidateMode",
    "CandidateSetResult",
    "FLEXIBLE_LATEST_START_MULTIPLIER",
    "MetricStatus",
    "MetricValue",
    "PathSpec",
    "ReleaseStatus",
    "Reservation",
    "ReservationRequest",
    "ReservationValidationError",
    "SOFT_LATEST_START_MULTIPLIER",
    "SlaLimits",
    "SlaPolicy",
    "SlaType",
    "TASK_SCHEMA_VERSION",
    "TariffConverter",
    "TaskRuntime",
    "TaskSpec",
    "TaskValidationResult",
    "TaskState",
    "TaskValidationError",
    "TimeConverter",
    "TimeInterval",
    "UnitValidationError",
    "cpu_work_cpu_hours",
    "cpu_work_sim_units",
    "migrate_legacy_task",
    "validate_task_mapping",
    "to_legacy_task_dict",
    "validate_scheduling_grid",
    "canonical_edge",
]
